name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
        npm install @babel/plugin-proposal-private-property-in-object --save-dev

    - name: Set CI environment variable to false
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Build the React app
      run: CI=false npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
