name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t reactappdockerfile .
          docker images
          ls
          cd ./
          ls

      # Save Docker image as artifact
      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-react-app-image
          path: reactappdockerfile